# Sample .travis.yml for R projects

language: r
bioc_required: yes
warnings_are_errors: true

r_check_args: --as-cran

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
