comment: false
codecov:
  token: 7915b1ac-d4e1-4c48-b891-2ac3b4fd7c13

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
